websites_dict = {
    "google": "https://www.google.com/",
    "kabarak": "https://www.kabarak.ac.ke/",
    "gmail": "https://mail.google.com/mail/u/0/#inbox",
    "myclass": "https://myclass.lpu.in/",
    "github": "https://github.com/",
    "youtube": "https://www.youtube.com/",
    "sanfoundry": "https://www.sanfoundry.com/",
    "hackerrank": "https://www.hackerrank.com/dashboard",
    "hackerearth": "https://www.hackerearth.com/challenges/",
    "codeforces": "https://codeforces.com/enter?back=%2Fproblemset",
    "codechef": "https://www.codechef.com/",
    "codecademy": "https://www.codecademy.com/catalog",
    "leetcode": "https://leetcode.com/",
    "udemy": "https://www.udemy.com/",
    "coursera": "https://www.coursera.org/",
    "w3resource": "https://www.w3resource.com/",
    "w3schools": "https://www.w3schools.com/",
    "geeksforgeeks": "https://www.geeksforgeeks.org/",
    "stackoverflow": "https://stackoverflow.com/",
    "instagram": "https://www.instagram.com/?hl=en",
    "facebook": "https://www.facebook.com/",
    "linkedin": "https://www.linkedin.com/",
    "twitter": "https://twitter.com/LOGIN",
    "netflix": "https://netflix.com/",
    "amazon prime": "https://primevideo.com/",
    "whatsapp": "https://web.whatsapp.com/",
    "hotstar": "https://www.hotstar.com/",
    "cricbuzz": "https://www.cricbuzz.com/",
    "google maps": "https://maps.google.com/",
    "flipkart": "https://www.flipkart.com/",
    "amazon": "https://www.amazon.com/",
    "nykaa": "https://www.nykaa.com/",
    "myntra": "https://www.myntra.com/",
    "amazon flex": "https://flex.amazon.in/",
    "swiggy": "https://www.swiggy.com/",
    "spotify": "https://open.spotify.com/"
}